<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_login</name>
   <tag></tag>
   <elementGuidId>f312d639-6df9-4c2b-bc9c-e664125c27e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.button.button-large.button-solid-norm.w100.mt1-75</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a2c9e5f1-3b74-423b-96d9-d0beddc3f653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button-large button-solid-norm w100 mt1-75</value>
      <webElementGuid>63a9a949-9e6d-4227-8a69-5612028f72e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-busy</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0f213a45-cfa0-4028-a49d-b66f1a5f68e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d30cca9d-6c8e-42fe-86f3-3dc2004e320f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Iniciar sesión</value>
      <webElementGuid>b91dbafa-fb0c-4da6-acd0-d127e25cd9ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;app-root&quot;]/div[@class=&quot;ui-prominent bg-norm color-norm h100 flex-no-min-children flex-nowrap flex-column h100 sign-layout-bg scroll-if-needed&quot;]/div[@class=&quot;pl2 pr2 sign-layout-container flex-item-fluid flex flex-nowrap flex-column flex-justify-space-between&quot;]/div[1]/main[@class=&quot;ui-standard color-norm bg-norm relative no-scroll w100 max-w100 center sign-layout mw30r&quot;]/div[@class=&quot;sign-layout-main-content&quot;]/form[1]/button[@class=&quot;button button-large button-solid-norm w100 mt1-75&quot;]</value>
      <webElementGuid>ebb0a733-8b11-41cb-bf59-d46d92db2cdb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>272717ad-1bd5-4097-b9f6-30c333bff829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Más información'])[1]/following::button[1]</value>
      <webElementGuid>102a843b-431d-4229-ad62-027be0b76803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Más información: Seguirás conectado incluso después de cerrar el navegador.'])[1]/following::button[1]</value>
      <webElementGuid>0a520868-ca7e-4c3c-b5ae-ed20693e9e25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Crear una cuenta'])[1]/preceding::button[1]</value>
      <webElementGuid>94debf29-5c03-4aea-af42-ffeebe75d5c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>fe01eac3-5b4f-431d-8030-14bbbfc61ce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Iniciar sesión' or . = 'Iniciar sesión')]</value>
      <webElementGuid>509ba0b7-9420-4b28-ba83-2bc6588bb788</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
