<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_staySignedIn</name>
   <tag></tag>
   <elementGuidId>7a505366-b932-416c-a0ff-c08773ccfe93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#staySignedIn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='staySignedIn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8ac08e45-547c-4a5e-99c6-479365d1ff3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>staySignedIn</value>
      <webElementGuid>036bb27b-a3d3-4b3c-b6d8-6eab53159e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b4c26ecc-e684-402c-8e2a-41872fa29104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-input</value>
      <webElementGuid>9859ec69-6071-439c-845f-1ca2d9cfe457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;staySignedIn&quot;)</value>
      <webElementGuid>fc579101-9e73-4a3d-8a8d-d66ace545cc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='staySignedIn']</value>
      <webElementGuid>06b74856-36f9-4a8a-8005-8aed4236a6cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>88ed196c-bb1e-4b78-9d79-7aa2632b20f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'staySignedIn' and @type = 'checkbox']</value>
      <webElementGuid>3f743110-c341-4b2f-bd14-2dd2ea7c13e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
