<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Reenviar_w100</name>
   <tag></tag>
   <elementGuidId>6d206b6e-1c64-42fd-b02e-1f08f4e50a97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe.w100</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>21ceeaa9-9ee2-48aa-bacc-ad996c7db70d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Contenido del correo electrónico</value>
      <webElementGuid>dabef48e-1928-46a7-9e71-00885d52a5dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>about:blank</value>
      <webElementGuid>9149614e-714b-463b-b6bc-7cff25635fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>360ee63e-01c9-43a1-8c7d-d2c304e53cc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>749a21bf-5f70-4d60-8d32-f8a5c3f701ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w100</value>
      <webElementGuid>7376f5d7-cf67-43b5-afa9-b09a1d5276c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>content-iframe</value>
      <webElementGuid>43ffcf12-59ca-46e3-8cb3-9ea88f2acb60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-subject</name>
      <type>Main</type>
      <value>VisualVault - New Account Created</value>
      <webElementGuid>ac73adbb-48db-4c6f-8f2a-325ed9293e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-same-origin allow-popups allow-popups-to-escape-sandbox</value>
      <webElementGuid>1c2bb38a-dfae-478a-b39a-76132dfcb2c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;is-comfortable&quot;]/div[@class=&quot;app-root&quot;]/div[@class=&quot;content-container flex flex-column flex-nowrap no-scroll&quot;]/div[@class=&quot;content ui-prominent flex-item-fluid-auto flex flex-column flex-nowrap reset4print&quot;]/div[@class=&quot;flex flex-item-fluid flex-nowrap&quot;]/div[@class=&quot;main ui-standard flex flex-column flex-nowrap flex-item-fluid&quot;]/div[@class=&quot;flex-item-fluid flex flex-column flex-nowrap outline-none&quot;]/main[@class=&quot;main-area--with-toolbar flex-item-fluid-auto relative flex&quot;]/section[@class=&quot;view-column-detail flex flex-column flex-item-fluid flex-nowrap relative no-scroll&quot;]/div[@class=&quot;scroll-outer-vertical&quot;]/div[@class=&quot;scroll-inner&quot;]/div[@class=&quot;scroll-child&quot;]/div[@class=&quot;flex-item-fluid pt1 pr1 pl1 w100&quot;]/div[@class=&quot;outline-none pb-custom&quot;]/article[@class=&quot;message-container m0-5 mb1 outline-none relative is-opened&quot;]/div[@class=&quot;message-content relative bg-norm color-norm pt1 pb1 px1-25 dark-style&quot;]/div[@class=&quot;message-iframe p1&quot;]/iframe[@class=&quot;w100&quot;]</value>
      <webElementGuid>9bea16e9-3c0b-419a-90b9-77aa83fa0f48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>e52dec0f-17cb-47c8-9237-1a7a26e12c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'Contenido del correo electrónico' and @src = 'about:blank']</value>
      <webElementGuid>58429190-deb3-434b-aa9a-f64648a13f70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
