<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>new_email_obj</name>
   <tag></tag>
   <elementGuidId>5f1232a4-7292-46e3-b7ee-5b192dfb3095</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.item-senders.flex-item-fluid.flex.flex-nowrap.pr1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='V'])[1]/following::div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dd8b2106-366a-489f-8c26-733c6fb1ff48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-senders flex-item-fluid flex flex-nowrap pr1</value>
      <webElementGuid>6e582b02-f9bb-441e-867a-c8dac9d1635b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>VisualVault</value>
      <webElementGuid>243f8d22-e312-4aa5-bb48-b871d0533969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;is-comfortable&quot;]/div[@class=&quot;app-root&quot;]/div[@class=&quot;content-container flex flex-column flex-nowrap no-scroll&quot;]/div[@class=&quot;content ui-prominent flex-item-fluid-auto flex flex-column flex-nowrap reset4print&quot;]/div[@class=&quot;flex flex-item-fluid flex-nowrap&quot;]/div[@class=&quot;main ui-standard flex flex-column flex-nowrap flex-item-fluid&quot;]/div[@class=&quot;flex-item-fluid flex flex-column flex-nowrap outline-none&quot;]/main[@class=&quot;main-area--with-toolbar flex-item-fluid-auto relative flex&quot;]/div[@class=&quot;relative items-column-list relative&quot;]/div[@class=&quot;h100 scroll-if-needed scroll-smooth-touch&quot;]/div[@class=&quot;items-column-list-inner flex flex-nowrap flex-column relative&quot;]/div[@class=&quot;flex flex-nowrap flex-align-items-center cursor-pointer item-container item-is-selected read&quot;]/div[@class=&quot;flex-item-fluid flex flex-nowrap flex-column flex-justify-center item-titlesender&quot;]/div[@class=&quot;flex flex-align-items-center item-firstline&quot;]/div[@class=&quot;item-senders flex-item-fluid flex flex-nowrap pr1&quot;]</value>
      <webElementGuid>270dda08-1f80-436b-9369-9a43ac85b63e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='V'])[1]/following::div[3]</value>
      <webElementGuid>cb4c3700-604f-47d0-8b87-f93cd516572e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Más recientes primero'])[1]/following::div[4]</value>
      <webElementGuid>988b0a71-bc27-4529-822a-2c5e7317183c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Destacar conversación'])[1]/preceding::div[1]</value>
      <webElementGuid>5f670906-9543-4bf1-97af-3200055f1463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div/div/div</value>
      <webElementGuid>17f1ce9c-9cef-46dd-9a71-c3eb8848feb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'VisualVault' or . = 'VisualVault')]</value>
      <webElementGuid>b0130503-d44e-420f-99d7-76436d47c23c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
